version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bookstore
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # book-service:
  #   build: ./services/book-service
  #   ports:
  #     - "3002:3002"
  #   depends_on:
  #     - db

  # backend:
  #   build: ./backend
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - book-service

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "5173:5173"
  #   depends_on:

  #     - backend

volumes:
  pgdata:
