version: '3.8'

services:
  auth-db:
    image: postgres:15
    container_name: auth-db
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - auth_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  book-db:
    image: postgres:15
    container_name: book-db
    environment:
      POSTGRES_DB: bookdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - book_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  auth-service:
    build: ./services/auth-service
    env_file:
      - ./services/auth-service/.env
    depends_on:
      - auth-db
    ports:
      - "3001:3001"

  book-service:
    build: ./services/book-service
    env_file:
      - ./services/book-service/.env
    depends_on:
      - book-db
    ports:
      - "3002:3002"

  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    depends_on:
      - auth-service
      - book-service
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    ports:
      - "3020:80"
    depends_on:
      - backend

  init:
    build: ./init
    depends_on:
      - auth-service
      - book-service
    entrypoint: ["/bin/sh", "-c", "/app/init.sh"]
    volumes:
      - ./init:/app
      - ./services/auth-service:/auth-service
      - ./services/book-service:/book-service


volumes:
  auth_data:
  book_data:
